=== zepalmer/bsj/compiler/source-generator/data/srcgen/srcgen.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="typeMode_T">
        <xs:restriction base="xs:string">
            <xs:enumeration value="tag" />
            <xs:enumeration value="abstract" />
            <xs:enumeration value="concrete" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="propMode_T">
        <xs:restriction base="xs:string">
            <xs:enumeration value="normal" />
            <xs:enumeration value="readOnly" />
            <xs:enumeration value="skip" />
            <xs:enumeration value="hide" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nogenArg_T">
        <xs:restriction base="xs:string">
            <xs:enumeration value="cons" />
            <xs:enumeration value="children" />
            <xs:enumeration value="replace" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="interface_T">
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="tag_T">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="typeArg" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="abstractProp_T">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:attribute name="typeArg" type="xs:string" use="optional" />
        <xs:attribute name="desc" type="xs:string" use="required" />
        <xs:attribute name="default" type="xs:string" use="optional" />
        <xs:attribute name="allowUnion" type="xs:string" use="optional" default="true" />
    </xs:complexType>

    <xs:complexType name="constant_T">
        <xs:complexContent>
            <xs:extension base="abstractProp_T">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="prop_T">
        <xs:complexContent>
            <xs:extension base="abstractProp_T">
                <xs:attribute name="mode" type="propMode_T" use="optional" default="normal" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="diagnosticProp_T">
        <xs:complexContent>
            <xs:extension base="abstractProp_T">
                <xs:attribute name="mode" type="propMode_T" use="optional" default="normal" />
                <xs:attribute name="messageExpression" type="xs:string" use="optional" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="include_T">
        <xs:attribute name="file" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="doc_T">
        <xs:simpleContent>
            <xs:extension base="xs:string">
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="code_T">
        <xs:simpleContent>
            <xs:extension base="xs:string">
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="override_T">
        <xs:attribute name="prop" type="xs:string" use="required" />
        <xs:attribute name="expr" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="nogen_T">
        <xs:attribute name="id" type="nogenArg_T" use="required" />
    </xs:complexType>

    <xs:complexType name="factoryMethod_prop_T">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="visible" type="xs:boolean" use="optional" default="true" />
    </xs:complexType>

    <xs:complexType name="factoryMethod_useDefaults_T">
    </xs:complexType>

    <xs:complexType name="factoryMethod_T">
        <xs:choice>
            <xs:sequence>
                <xs:element name="prop" type="factoryMethod_prop_T" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:sequence>
                <xs:element name="use-defaults" type="factoryMethod_useDefaults_T" />
            </xs:sequence>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="defaults_T">
        <xs:attribute name="typeMode" type="xs:string" use="optional" />
        <xs:attribute name="propertyMode" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="factory_T">
        <xs:attribute name="interface" type="xs:string" use="required" />
        <xs:attribute name="class" type="xs:string" use="required" />
        <xs:attribute name="decorator" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="type_T">
        <xs:sequence>
            <xs:element name="interface" type="interface_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="tag" type="tag_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="constant" type="constant_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="prop" type="prop_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="include" type="include_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="doc" type="doc_T" />
            <xs:element name="constructorFooter" type="code_T" minOccurs="0" maxOccurs="1" />
            <xs:element name="toString" type="code_T" minOccurs="0" maxOccurs="1" />
            <xs:element name="factory-override" type="override_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="constructor-override" type="override_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="nogen" type="nogen_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="factory-method" type="factoryMethod_T" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="typeParam" type="xs:string" use="optional" />
        <xs:attribute name="super" type="xs:string" use="optional" />
        <xs:attribute name="superTypeArg" type="xs:string" use="optional" />
        <xs:attribute name="mode" type="typeMode_T" use="optional" default="concrete" />
    </xs:complexType>

    <xs:complexType name="diagnosticException_T">
        <xs:sequence>
            <xs:element name="doc" type="doc_T" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="prop" type="xs:string" use="optional" default="exception" />
    </xs:complexType>

    <xs:complexType name="diagnosticMessageProp_T">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="expression" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="diagnostic_T">
        <xs:sequence>
            <xs:element name="exception" type="diagnosticException_T" minOccurs="0" maxOccurs="1" />
            <xs:element name="prop" type="diagnosticProp_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="messageProp" type="diagnosticMessageProp_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="doc" type="doc_T" />
            <xs:element name="constructorFooter" type="code_T" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="typeParam" type="xs:string" use="optional" />
        <xs:attribute name="super" type="xs:string" use="optional" />
        <xs:attribute name="superTypeArg" type="xs:string" use="optional" />
        <xs:attribute name="code" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="userDiagnostic_T">
        <xs:sequence>
            <xs:element name="prop" type="diagnosticProp_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="messageProp" type="diagnosticMessageProp_T" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="doc" type="doc_T" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="typeParam" type="xs:string" use="optional" />
        <xs:attribute name="super" type="xs:string" use="optional" />
        <xs:attribute name="superTypeArg" type="xs:string" use="optional" />
        <xs:attribute name="code" type="xs:string" use="optional" />
    </xs:complexType>
    
    <xs:complexType name="outputType_T">
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
    
    <xs:complexType name="parserule_T">
        <xs:sequence>
            <xs:element name="outputType" type="outputType_T" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="import_T">
        <xs:attribute name="path" type="xs:string" use="required" />
    </xs:complexType>

    <xs:simpleType name="project_T">
        <xs:restriction base="xs:string">
            <xs:enumeration value="api" />
            <xs:enumeration value="parser" />
            <xs:enumeration value="generator" />
            <xs:enumeration value="bsjutils" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="srcgen_T">
        <xs:choice>
            <xs:sequence>
                <xs:element name="defaults" type="defaults_T" minOccurs="0" maxOccurs="1" />
                <xs:element name="factory" type="factory_T" minOccurs="0" maxOccurs="1" />
                <xs:choice>
                    <xs:sequence>
                        <xs:element name="srcgen" type="srcgen_T" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                    <xs:sequence>
                        <xs:element name="type" type="type_T" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:choice>
            </xs:sequence>
            <xs:sequence>
                <xs:element name="diagnostic" type="diagnostic_T" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:sequence>
                <xs:element name="userDiagnostic" type="userDiagnostic_T" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:sequence>
                <xs:element name="parserule" type="parserule_T" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:sequence>
                <xs:element name="import" type="import_T" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:choice>
        <xs:attribute name="ipkg" type="xs:string" use="optional" />
        <xs:attribute name="cpkg" type="xs:string" use="optional" />
        <xs:attribute name="itgt" type="project_T" use="optional" default="api" />
        <xs:attribute name="ctgt" type="project_T" use="optional" default="generator" />
        <xs:attribute name="bsjSpecific" type="xs:boolean" use="optional" default="false" />
    </xs:complexType>

    <xs:element name="srcgen" type="srcgen_T" />
</xs:schema>

=== zepalmer/bsj/compiler/source-generator/data/srcgen/userdiagnostic.xml
<srcgen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./srcgen.xsd">
    <srcgen>
        <srcgen ipkg="edu.jhu.cs.bsj.stdlib.diagnostic" cpkg="edu.jhu.cs.bsj.stdlib.diagnostic.impl"
            itgt="bsjutils" ctgt="bsjutils">
            <userDiagnostic name="InvalidMetaAnnotationUseDiagnostic" super="BsjUtilDiagnostic">
                <prop name="metaAnnotationClass" type="Class&lt;? extends AbstractBsjMetaAnnotationMetaprogram&gt;"
                    desc="the class of meta-annotation that was used incorrectly" />
                <doc><![CDATA[
                    A diagnostic indicating that a meta-annotation is used incorrectly.
                ]]></doc>
            </userDiagnostic>

            <userDiagnostic name="InvalidAnnotatedDeclarationDiagnostic" super="InvalidMetaAnnotationUseDiagnostic"
                code="bsj.stdlib.metaannotation.invalid.declaration.type">
                <prop name="annotatedNode" type="Node" desc="the node that was annotated" />
                <prop name="legalTypes" type="List&lt;Class&lt;? extends Node&gt;&gt;"
                    desc="the legal types that could be annotated by the meta-annotation" />
                <messageProp expression="annotatedNode!=null?annotatedNode.getClass().getName():null" />
                <doc><![CDATA[
                    Indicates that the meta-annotation cannot be used on the specified type of node.  The
                    <code>annotatedNode</code> field is a hint and may be <code>null</code>.
                ]]></doc>
            </userDiagnostic>

            <userDiagnostic name="InvalidEnclosingTypeDiagnostic" super="InvalidMetaAnnotationUseDiagnostic"
                code="bsj.stdlib.metaannotation.invalid.enclosing.type">
                <prop name="node" type="TypeDeclarationNode" desc="the enclosing type declaration" />
                <prop name="legalTypes" type="List&lt;Class&lt;? extends TypeDeclarationNode&gt;&gt;"
                    desc="the legal types that could be annotated by the meta-annotation" />
                <messageProp expression="node!=null?node.getClass().getName():null" />
                <doc><![CDATA[
                    Indicates that the meta-annotation cannot be used in the enclosing type in which it is found.  The
                    <code>enclosingNode</code> field is a hint and may be <code>null</code> (especially if the
                    meta-annotation is attached to a code fragment and not a descendent of the root package).
                ]]></doc>
            </userDiagnostic>
        </srcgen>
    </srcgen>
</srcgen>

=== zepalmer/bsj/compiler/source-generator/data/srcgen/diagnostic.xml
<srcgen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./srcgen.xsd">
    <!-- Diagnostics -->
    <srcgen>
        <srcgen cpkg="edu.jhu.cs.bsj.compiler.diagnostic.lexer">
            <diagnostic name="BsjLexerDiagnostic">
                <prop name="character" type="int" desc="the character which caused this diagnostic" />
                <doc><![CDATA[
                    A diagnostic which acts as a supertype for all BSJ lexer diagnostics.
                ]]></doc>
            </diagnostic>

            <diagnostic name="GeneralLexerFailureDiagnostic" code="lexer.error.generalFailure"
                super="BsjLexerDiagnostic">
                <doc><![CDATA[
                    A diagnostic indicating a general lexer failure.
                ]]></doc>
            </diagnostic>
        </srcgen>

        <srcgen cpkg="edu.jhu.cs.bsj.compiler.diagnostic.parser">
            <diagnostic name="BsjParserDiagnostic">
                <prop name="ruleName" type="String" desc="the rule which caused this diagnostic" />
                <doc><![CDATA[
                    A diagnostic which acts as the parent for all parser diagnostics.
                ]]></doc>
            </diagnostic>

            <diagnostic name="ConflictingAccessModifierDiagnostic" code="bsj.parser.error.conflictingAccessModifier"
                super="BsjParserDiagnostic">
                <prop name="firstModifier" type="String" desc="the first modifier which conflicts" />
                <prop name="secondModifier" type="String" desc="the second modifier which conflicts" />
                <doc><![CDATA[
                    A diagnostic which represents a conflicting access modifier.
                ]]></doc>
            </diagnostic>

            <diagnostic name="DuplicateModifierDiagnostic" code="bsj.parser.error.duplicateModifier"
                super="BsjParserDiagnostic">
                <prop name="modifier" type="String" desc="the modifier which was duplicated" />
                <doc><![CDATA[
                    A diagnostic representing a duplicated modifier.
                ]]></doc>
            </diagnostic>

            <diagnostic name="ExtraneousTokenDiagnostic" code="bsj.parser.error.extraneousToken"
                super="BsjParserDiagnostic">
                <prop name="extraneousType" type="String" desc="the type of the extraneous token" />
                <prop name="extraneousToken" type="String" desc="the text of the extraneous token" />
                <doc><![CDATA[
                    A diagnostic representing the presence of an extraneous token.
                ]]></doc>
            </diagnostic>

            <diagnostic name="FloatingPointLiteralTooLargeDiagnostic" code="bsj.parser.error.invalidFloatingPointLiteral.tooLarge"
                super="InvalidFloatingPointLiteralDiagnostic">
                <doc><![CDATA[
                    A diagnostic indicating that a floating point literal was too large to fit into its type.
                ]]></doc>
            </diagnostic>

            <diagnostic name="FloatingPointLiteralTooSmallDiagnostic" code="bsj.parser.error.invalidFloatingPointLiteral.tooSmall"
                super="InvalidFloatingPointLiteralDiagnostic">
                <doc><![CDATA[
                    A diagnostic indicating that a floating point literal was too small to fit into its type.
                ]]></doc>
            </diagnostic>

            <diagnostic name="GeneralParseFailureDiagnostic" code="bsj.parser.error.generalParseFailure"
                super="BsjParserDiagnostic">
                <prop name="tokenType" type="String" desc="the type of the token where the errors started" />
                <prop name="tokenText" type="String" desc="the text of the token where the errors started" />
                <doc><![CDATA[
                    A diagnostic representing a general parsing failure starting at a given location.
                ]]></doc>
            </diagnostic>

            <diagnostic name="InvalidFloatingPointLiteralDiagnostic" super="BsjParserDiagnostic">
                <prop name="literalText" type="String" desc="the text of the invalid literal" />
                <doc><![CDATA[
                    A diagnostic representing an invalid floating point literal.
                ]]></doc>
            </diagnostic>

            <diagnostic name="InvalidIntegerLiteralDiagnostic" code="bsj.parser.error.invalidIntegerLiteral"
                super="BsjParserDiagnostic">
                <prop name="literalText" type="String" desc="the text of the invalid literal" />
                <doc><![CDATA[
                    A diagnostic representing an invalid floating point literal.
                ]]></doc>
            </diagnostic>

            <diagnostic name="InvalidModifierDiagnostic" code="bsj.parser.error.invalidModifier"
                super="BsjParserDiagnostic">
                <prop name="modifier" type="String" desc="the modifier which was used incorrectly" />
                <doc><![CDATA[
                    A diagnostic representing an invalid modifier (a modifier which appeared in an incorrect context).
                ]]></doc>
            </diagnostic>

            <diagnostic name="MissingTokenDiagnostic" code="bsj.parser.error.missingToken" super="BsjParserDiagnostic">
                <prop name="tokenType" type="String" desc="the type of the missing token" />
                <doc><![CDATA[
                    A diagnostic representing a missing token.
                ]]></doc>
            </diagnostic>

            <diagnostic name="UnexpectedTokenDiagnostic" code="bsj.parser.error.unexpectedToken"
                super="BsjParserDiagnostic">
                <prop name="tokenType" type="String" desc="the type of the token which was found" />
                <prop name="tokenText" type="String" desc="the text of the token which was found" />
                <prop name="expectedType" type="String" desc="the type of the expected token" />
                <doc><![CDATA[
                    A diagnostic representing the presence of one token where another was expected.
                ]]></doc>
            </diagnostic>

            <diagnostic name="UnqualifiedSingleStaticImportNameDiagnostic" code="bsj.parser.error.invalidSingleStaticImportName"
                super="BsjParserDiagnostic">
                <prop name="name" type="String" desc="the name which was provided" />
                <doc><![CDATA[
                    A diagnostic representing a single static import which used an unqualified name.
                ]]></doc>
            </diagnostic>
        </srcgen>
    </srcgen>
</srcgen>
